/*****
 * 
 * Copyright (c) 2024 Radius Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
*****/

(() => {
    const languages = [
        {iso1: '**', iso2: '',    iso: "None",                      local: "None"},
        {iso1: 'aa', iso2: 'aar', iso: "Afar",                      local: "Afaraf"},
        {iso1: 'ab', iso2: 'abk', iso: "Abkhazian",                 local: "аҧсуа бызшәа, аҧсшәа"},
        {iso1: '',   iso2: 'ace', iso: "Achinese",                  local: ""},
        {iso1: '',   iso2: 'ach', iso: "Acoli",                     local: ""},
        {iso1: '',   iso2: 'ada', iso: "Adangme",                   local: ""},
        {iso1: '',   iso2: 'ady', iso: "Adyghe; Adygei",            local: ""},
        {iso1: '',   iso2: 'afa', iso: "Afro-Asiatic Langueges",    local: ""},
        {iso1: '',   iso2: 'afh', iso: "Afrihili",                  local: ""},
        {iso1: 'af', iso2: 'afr', iso: "Afrikaans",                 local: "Afrikaans"},
        {iso1: '',   iso2: 'ain', iso: "Ainu",                      local: ""},
        {iso1: 'ak', iso2: 'aka', iso: "Akan",                      local: "Akan"},
        {iso1: '',   iso2: 'akk', iso: "Akadian",                   local: ""},
        {iso1: 'sq', iso2: 'alb', iso: "Albanian",                  local: "Shqip"},
        {iso1: 'sq', iso2: 'sqi', iso: "Albanian",                  local: "Shqip"},
        {iso1: '',   iso2: 'ale', iso: "Aleut",                     local: ""},
        {iso1: '',   iso2: 'alg', iso: "Algonquian Languages",      local: ""},
        {iso1: '',   iso2: 'alt', iso: "Southern Altai",            local: ""},
        {iso1: 'am', iso2: 'amh', iso: "Amharic",                   local: "አማርኛ"},
        {iso1: '',   iso2: 'ang', iso: "Old English",               local: ""},
        {iso1: '',   iso2: 'anp', iso: "Angika",                    local: ""},
        {iso1: '',   iso2: 'apa', iso: "Apacke Languages",          local: ""},
        {iso1: 'ar', iso2: 'ara', iso: "Arabic",                    local: "العربية"},
        {iso1: '',   iso2: 'arc', iso: "Aramaic",                   local: ""},
        {iso1: 'an', iso2: 'arg', iso: "Aragonese",                 local: "aragonés"},
        {iso1: 'hy', iso2: 'arm', iso: "Armenian",                  local: "Հայերեն"},
        {iso1: 'hy', iso2: 'hye', iso: "Armenian",                  local: "Հայերեն"},
        {iso1: '',   iso2: 'arn', iso: "Mapudungan",                local: ""},
        {iso1: '',   iso2: 'arp', iso: "Arapaho",                   local: ""},
        {iso1: '',   iso2: 'art', iso: "Artificial Languages",      local: ""},
        {iso1: '',   iso2: 'arw', iso: "Arawak",                    local: ""},
        {iso1: 'as', iso2: 'asm', iso: "Assamese",                  local: "অসমীয়া"},
        {iso1: '',   iso2: 'ast', iso: "Asturian",                  local: ""},
        {iso1: '',   iso2: 'ath', iso: "Athapascan Languages",      local: ""},
        {iso1: '',   iso2: 'aus', iso: "Australian",                local: ""},
        {iso1: 'av', iso2: 'ava', iso: "Ava",                       local: "авар мацӀ, магӀарул мацӀ"},
        {iso1: 'ae', iso2: 'ave', iso: "Avestan",                   local: "avesta"},
        {iso1: '',   iso2: 'awa', iso: "Awadhi",                    local: ""},
        {iso1: 'ay', iso2: 'aym', iso: "Aymara",                    local: "aymar aru"},
        {iso1: 'az', iso2: 'aze', iso: "Azerbaijani",               local: "azərbaycan dili"},
        {iso1: '',   iso2: 'bad', iso: "Banda Languages",           local: ""},
        {iso1: '',   iso2: 'bai', iso: "Bamileke Languages",        local: ""},
        {iso1: 'ba', iso2: 'bak', iso: "Bashkir",                   local: "башҡорт теле"},
        {iso1: '',   iso2: 'bao', iso: "Baluchi",                   local: ""},
        {iso1: 'bm', iso2: 'bam', iso: "Bambara",                   local: "bamanankan"},
        {iso1: '',   iso2: 'ban', iso: "Balinese",                  local: ""},
        {iso1: 'eu', iso2: 'baq', iso: "Basque",                    local: "euskara, euskera"},
        {iso1: 'eu', iso2: 'eus', iso: "Basque",                    local: "euskara, euskera"},
        {iso1: '',   iso2: 'bas', iso: "Basa",                      local: ""},
        {iso1: '',   iso2: 'bat', iso: "Baltic Languages",          local: ""},
        {iso1: '',   iso2: 'bej', iso: "Beja",                      local: ""},
        {iso1: 'be', iso2: 'bel', iso: "Belurusian",                local: "беларуская мова"},
        {iso1: '',   iso2: 'bem', iso: "Bemba",                     local: ""},
        {iso1: 'bn', iso2: 'ben', iso: "Bengali",                   local: "বাংলা"},
        {iso1: '',   iso2: 'ber', iso: "Berber Languages",          local: ""},
        {iso1: '',   iso2: 'bho', iso: "Bhojpuri",                  local: ""},
        {iso1: 'bh', iso2: 'bih', iso: "Bihari Languages",          local: "भोजपुरी"},
        {iso1: '',   iso2: 'bik', iso: "Bikol",                     local: ""},
        {iso1: '',   iso2: 'bin', iso: "Bini; Edol",                local: ""},
        {iso1: 'bi', iso2: 'bis', iso: "Bislama",                   local: "Bislama"},
        {iso1: '',   iso2: 'bla', iso: "Siksika",                   local: ""},
        {iso1: '',   iso2: 'bnt', iso: "Bantu Languages",           local: ""},
        {iso1: 'bo', iso2: 'bod', iso: "Tibetan",                   local: "བོད་ཡིག"},
        {iso1: 'bo', iso2: 'tib', iso: "Tibetan",                   local: "བོད་ཡིག"},
        {iso1: 'bs', iso2: 'bos', iso: "Bosnian",                   local: "bosanski jezik"},
        {iso1: '',   iso2: 'bra', iso: "Braj",                      local: ""},
        {iso1: 'br', iso2: 'bre', iso: "Breton",                    local: "brezhoneg"},
        {iso1: '',   iso2: 'btk', iso: "Batak Languages",           local: ""},
        {iso1: '',   iso2: 'bua', iso: "Buriat",                    local: ""},
        {iso1: '',   iso2: 'bug', iso: "Buginese",                  local: ""},
        {iso1: 'bg', iso2: 'bul', iso: "Bulgarian",                 local: "български език"},
        {iso1: 'my', iso2: 'bur', iso: "Burmese",                   local: "ဗမာစာ"},
        {iso1: 'my', iso2: 'mya', iso: "Burmese",                   local: "ဗမာစာ"},
        {iso1: '',   iso2: 'byn', iso: "Bin: Bilin",                local: ""},
        {iso1: '',   iso2: 'cad', iso: "Cado",                      local: ""},
        {iso1: '',   iso2: 'cai', iso: "Central American Indian",   local: ""},
        {iso1: '',   iso2: 'car', iso: "Galibi Carib",              local: ""},
        {iso1: 'ca', iso2: 'cat', iso: "Catalan",                   local: "català"},
        {iso1: '',   iso2: 'cau', iso: "Caucasian Languages",       local: ""},
        {iso1: '',   iso2: 'ceb', iso: "Cebuano",                   local: ""},
        {iso1: '',   iso2: 'cel', iso: "Celtic",                    local: ""},
        {iso1: 'cs', iso2: 'cze', iso: "Czech",                     local: "čeština, český jazyk"},
        {iso1: 'cs', iso2: 'ces', iso: "Czech",                     local: "čeština, český jazyk"},
        {iso1: 'ch', iso2: 'cha', iso: "Chamorro",                  local: "Chamoru"},
        {iso1: '',   iso2: 'chb', iso: "Chibcha",                   local: ""},
        {iso1: 'ce', iso2: 'che', iso: "Chechen",                   local: "нохчийн мотт"},
        {iso1: '',   iso2: 'chg', iso: "Chagatai",                  local: ""},
        {iso1: 'zh', iso2: 'chi', iso: "Chinese",                   local: "中文, 汉语, 漢語"},
        {iso1: 'zh', iso2: 'zho', iso: "Chinese",                   local: "中文, 汉语, 漢語"},
        {iso1: '',   iso2: 'chk', iso: "Chuukese",                  local: ""},
        {iso1: '',   iso2: 'chm', iso: "Mari",                      local: ""},
        {iso1: '',   iso2: 'chn', iso: "Chinook jargon",            local: ""},
        {iso1: '',   iso2: 'cho', iso: "Chocktaw",                  local: ""},
        {iso1: '',   iso2: 'chp', iso: "Chipewyan",                 local: ""},
        {iso1: '',   iso2: 'chr', iso: "Cherokee",                  local: ""},
        {iso1: '',   iso2: 'chu', iso: "Church Slavic",             local: ""},
        {iso1: 'cv', iso2: 'chv', iso: "Chuvash",                   local: "чӑваш чӗлхи"},
        {iso1: '',   iso2: 'chy', iso: "Cheyenne",                  local: ""},
        {iso1: '',   iso2: 'cmc', iso: "Charmic Languages",         local: ""},
        {iso1: '',   iso2: 'cnr', iso: "Montenegrin",               local: ""},
        {iso1: '',   iso2: 'cop', iso: "Coptic",                    local: ""},
        {iso1: 'kw', iso2: 'cor', iso: "Cornish",                   local: "Kernewek"},
        {iso1: 'co', iso2: 'cos', iso: "Corsican",                  local: "corsu, lingua corsa"},
        {iso1: '',   iso2: 'cpe', iso: "Creoles, English",          local: ""},
        {iso1: '',   iso2: 'cpf', iso: "Creoles, French",           local: ""},
        {iso1: '',   iso2: 'cpp', iso: "Creoles, Portguguese",      local: ""},
        {iso1: 'cr', iso2: 'cre', iso: "Cree",                      local: "ᓀᐦᐃᔭᐍᐏᐣ"},
        {iso1: '',   iso2: 'crh', iso: "Crimean Tatar",             local: ""},
        {iso1: '',   iso2: 'crp', iso: "Creoles, Pidgin",           local: ""},
        {iso1: '',   iso2: 'csb', iso: "Kashubian",                 local: ""},
        {iso1: '',   iso2: 'cus', iso: "Cushitic Languages",        local: ""},
        {iso1: 'cy', iso2: 'wel', iso: "Welsh",                     local: "Cymraeg"},
        {iso1: 'cy', iso2: 'cym', iso: "Welsh",                     local: "Cymraeg"},
        {iso1: '',   iso2: 'dak', iso: "Dakota",                    local: ""},
        {iso1: 'da', iso2: 'dan', iso: "Danish",                    local: "dansk"},
        {iso1: '',   iso2: 'dar', iso: "Dargwa",                    local: ""},
        {iso1: '',   iso2: 'day', iso: "Land Dayak Languages",      local: ""},
        {iso1: '',   iso2: 'del', iso: "Delaware",                  local: ""},
        {iso1: '',   iso2: 'den', iso: "Slave",                     local: ""},
        {iso1: 'de', iso2: 'deu', iso: "German",                    local: "Deutsch"},
        {iso1: '',   iso2: 'dgr', iso: "Dogrib",                    local: ""},
        {iso1: '',   iso2: 'din', iso: "Dinka",                     local: ""},
        {iso1: 'dv', iso2: 'div', iso: "Divehi",                    local: "ދިވެހި"},
        {iso1: '',   iso2: 'doi', iso: "Dogri",                     local: ""},
        {iso1: '',   iso2: 'dra', iso: "Dravidian Languages",       local: ""},
        {iso1: '',   iso2: 'dsb', iso: "Lower Sorbian",             local: ""},
        {iso1: '',   iso2: 'dua', iso: "Duala",                     local: ""},
        {iso1: '',   iso2: 'dum', iso: "Middle Dutch",              local: ""},
        {iso1: 'nl', iso2: 'nld', iso: "Dutch",                     local: "Nederlands, Vlaams"},
        {iso1: 'nl', iso2: 'dut', iso: "Dutch",                     local: "Nederlands, Vlaams"},
        {iso1: '',   iso2: 'dyu', iso: "Dyula",                     local: ""},
        {iso1: 'dz', iso2: 'dzo', iso: "Dzongkha",                  local: "རྫོང་ཁ"},
        {iso1: '',   iso2: 'efi', iso: "Efik",                      local: ""},
        {iso1: '',   iso2: 'egy', iso: "Egyptian",                  local: ""},
        {iso1: '',   iso2: 'eka', iso: "Ekajuk",                    local: ""},
        {iso1: 'el', iso2: 'ell', iso: "Greek",                     local: "ελληνικά"},
        {iso1: 'el', iso2: 'gre', iso: "Greek",                     local: "ελληνικά"},
        {iso1: '',   iso2: 'elx', iso: "Elamite",                   local: ""},
        {iso1: 'en', iso2: 'eng', iso: "English",                   local: "English"},
        {iso1: '',   iso2: 'enm', iso: "Middle English",            local: ""},
        {iso1: 'eo', iso2: 'epo', iso: "Esperanto",                 local: "Esperanto"},
        {iso1: 'et', iso2: 'est', iso: "Estonian",                  local: "eesti, eesti keel"},
        {iso1: 'ee', iso2: 'ewe', iso: "Ewe",                       local: "Eʋegbe"},
        {iso1: '',   iso2: 'ewo', iso: "Ewondo",                    local: ""},
        {iso1: '',   iso2: 'fan', iso: "Fang",                      local: ""},
        {iso1: 'fo', iso2: 'fao', iso: "Faroese",                   local: "føroyskt"},
        {iso1: 'fa', iso2: 'per', iso: "Persian",                   local: "فارسی"},
        {iso1: 'fa', iso2: 'fas', iso: "Persian",                   local: "فارسی"},
        {iso1: '',   iso2: 'fat', iso: "Fanti",                     local: ""},
        {iso1: 'fj', iso2: 'fij', iso: "Fijian",                    local: "vosa Vakaviti"},
        {iso1: '',   iso2: 'fil', iso: "Phillipino",                local: ""},
        {iso1: 'fi', iso2: 'fin', iso: "Finnish",                   local: "suomi, suomen kieli"},
        {iso1: '',   iso2: 'fiu', iso: "Finno-Urgrian Languages",   local: ""},
        {iso1: '',   iso2: 'fon', iso: "Fon",                       local: ""},
        {iso1: 'fr', iso2: 'fre', iso: "French",                    local: "français"},
        {iso1: 'fr', iso2: 'fra', iso: "French",                    local: "français"},
        {iso1: '',   iso2: 'frm', iso: "Middle French",             local: ""},
        {iso1: '',   iso2: 'fro', iso: "Old French",                local: ""},
        {iso1: '',   iso2: 'frr', iso: "Northern Frisian",          local: ""},
        {iso1: '',   iso2: 'frs', iso: "Eastern Frisian",           local: ""},
        {iso1: 'fy', iso2: 'fry', iso: "Western Frisian",           local: "Frysk"},
        {iso1: 'ff', iso2: 'ful', iso: "Fulah",                     local: "Fulfulde, Pulaar, Pular"},
        {iso1: '',   iso2: 'fur', iso: "Friulian",                  local: ""},
        {iso1: '',   iso2: 'gaa', iso: "Ga",                        local: ""},
        {iso1: '',   iso2: 'gay', iso: "Gayo",                      local: ""},
        {iso1: '',   iso2: 'gba', iso: "Gbaya",                     local: ""},
        {iso1: '',   iso2: 'gem', iso: "Germanic Languages",        local: ""},
        {iso1: 'ka', iso2: 'geo', iso: "Georgian",                  local: "ქართული"},
        {iso1: 'ka', iso2: 'kat', iso: "Georgian",                  local: "ქართული"},
        {iso1: '',   iso2: 'gez', iso: "Geez",                      local: ""},
        {iso1: '',   iso2: 'gil', iso: "Gilbertese",                local: ""},
        {iso1: 'gd', iso2: 'gla', iso: "Gaelic",                    local: "Gàidhlig"},
        {iso1: 'ga', iso2: 'gle', iso: "Irish",                     local: "Gaeilge"},
        {iso1: 'gi', iso2: 'gig', iso: "Galician",                  local: "Galego"},
        {iso1: 'gv', iso2: 'glv', iso: "Manx",                      local: "Gaelg, Gailck"},
        {iso1: '',   iso2: 'gmh', iso: "Middle German",             local: ""},
        {iso1: '',   iso2: 'goh', iso: "Old German",                local: ""},
        {iso1: '',   iso2: 'gon', iso: "Gondi",                     local: ""},
        {iso1: '',   iso2: 'gor', iso: "Gorontalo",                 local: ""},
        {iso1: '',   iso2: 'got', iso: "Gothic",                    local: ""},
        {iso1: '',   iso2: 'grb', iso: "Grebo",                     local: ""},
        {iso1: '',   iso2: 'grc', iso: "Ancient Greek",             local: ""},
        {iso1: 'gn', iso2: 'grn', iso: "Guarani",                   local: "Avañe'ẽ"},
        {iso1: '',   iso2: 'gsw', iso: "Swiss German",              local: ""},
        {iso1: 'gu', iso2: 'guj', iso: "Gujarati",                  local: "ગુજરાતી"},
        {iso1: '',   iso2: 'gwi', iso: "Gwich'in",                  local: ""},
        {iso1: '',   iso2: 'hai', iso: "Haida",                     local: ""},
        {iso1: 'ht', iso2: 'hat', iso: "Hatian",                    local: "Kreyòl ayisyen"},
        {iso1: 'ha', iso2: 'hau', iso: "Hausa",                     local: "هَوُسَ"},
        {iso1: '',   iso2: 'haw', iso: "Hawaiian",                  local: ""},
        {iso1: 'he', iso2: 'heb', iso: "Hebrew",                    local: "עברית"},
        {iso1: 'hz', iso2: 'her', iso: "Herero",                    local: "Otjiherero"},
        {iso1: '',   iso2: 'hil', iso: "Hiligaynon",                local: ""},
        {iso1: '',   iso2: 'him', iso: "Himachali Languages",       local: ""},
        {iso1: 'hi', iso2: 'hin', iso: "Hindi",                     local: "हिन्दी, हिंदी"},
        {iso1: '',   iso2: 'hit', iso: "Hittite",                   local: ""},
        {iso1: '',   iso2: 'hmn', iso: "Hmong, Mong",               local: ""},
        {iso1: 'ho', iso2: 'hmo', iso: "Hiri Motu",                 local: "Hiri Motu"},
        {iso1: 'hr', iso2: 'hrv', iso: "Croatian",                  local: "hrvatski jezik"},
        {iso1: '',   iso2: 'hsb', iso: "Upper Sorbian",             local: ""},
        {iso1: 'hu', iso2: 'hun', iso: "Hungarian",                 local: "magyar"},
        {iso1: '',   iso2: 'hup', iso: "Hupa",                      local: ""},
        {iso1: '',   iso2: 'iba', iso: "Iban",                      local: ""},
        {iso1: 'ig', iso2: 'ibo', iso: "Igbo",                      local: "Asụsụ Igbo"},
        {iso1: 'is', iso2: 'ise', iso: "Icelandic",                 local: "Íslenska"},
        {iso1: 'io', iso2: 'ido', iso: "Ido",                       local: ""},
        {iso1: 'ii', iso2: 'iii', iso: "Sichuan Yi",                local: "ꆈꌠ꒿ Nuosuhxop"},
        {iso1: '',   iso2: 'ijo', iso: "Ijo Languages",             local: ""},
        {iso1: 'iu', iso2: 'iky', iso: "Inuktitut",                 local: "ᐃᓄᒃᑎᑐᑦ"},
        {iso1: 'ie', iso2: 'ile', iso: "Interlingue",               local: ""},
        {iso1: '',   iso2: 'ilo', iso: "Iloko",                     local: ""},
        {iso1: 'ia', iso2: 'ina', iso: "Interlingua",               local: ""},
        {iso1: '',   iso2: 'inc', iso: "Indic Languages",           local: ""},
        {iso1: 'id', iso2: 'ind', iso: "Indonesian",                local: "Bahasa Indonesia"},
        {iso1: '',   iso2: 'ine', iso: "Indo European",             local: ""},
        {iso1: '',   iso2: 'inh', iso: "Ingush",                    local: ""},
        {iso1: 'ik', iso2: 'ipk', iso: "Inupiaq",                   local: "Iñupiaq, Iñupiatun"},
        {iso1: '',   iso2: 'ira', iso: "Iranian Languages",         local: ""},
        {iso1: '',   iso2: 'iro', iso: "Iroquoian Languages",       local: ""},
        {iso1: 'it', iso2: 'ita', iso: "Italian",                   local: "Italiano"},
        {iso1: 'jv', iso2: 'jav', iso: "Javanese",                  local: "ꦧꦱꦗꦮ"},
        {iso1: '',   iso2: 'jbo', iso: "Lojban",                    local: ""},
        {iso1: 'ja', iso2: 'jpn', iso: "Japanese",                  local: "日本語 (にほんご)"},
        {iso1: '',   iso2: 'jpr', iso: "Judeo-Persian",             local: ""},
        {iso1: '',   iso2: 'jrb', iso: "Judeo-Arabic",              local: ""},
        {iso1: '',   iso2: 'kaa', iso: "Kara-Kalpak",               local: ""},
        {iso1: '',   iso2: 'kab', iso: "Kabyle",                    local: ""},
        {iso1: '',   iso2: 'kac', iso: "Kachin",                    local: ""},
        {iso1: 'kl', iso2: 'kal', iso: "Greenlandic",               local: "kalaallisut, kalaallit oqaasii"},
        {iso1: '',   iso2: 'kam', iso: "Kamba",                     local: ""},
        {iso1: 'kn', iso2: 'kan', iso: "Kannada",                   local: "ಕನ್ನಡ"},
        {iso1: '',   iso2: 'kar', iso: "Karen Languages",           local: ""},
        {iso1: 'ks', iso2: 'kas', iso: "Kashmiri",                  local: "कश्मीरी, كشميري‎"},
        {iso1: 'kr', iso2: 'kau', iso: "Kanuri",                    local: "Kanuri"},
        {iso1: '',   iso2: 'kaw', iso: "Kawi",                      local: ""},
        {iso1: 'kk', iso2: 'kaz', iso: "Kazakh",                    local: "қазақ тілі"},
        {iso1: '',   iso2: 'kbd', iso: "Kabardian",                 local: ""},
        {iso1: '',   iso2: 'kha', iso: "Khasi",                     local: ""},
        {iso1: '',   iso2: 'khi', iso: "Khoisan Languages",         local: ""},
        {iso1: 'km', iso2: 'khm', iso: "Central Khmer",             local: "ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ"},
        {iso1: '',   iso2: 'kho', iso: "Khotanese",                 local: ""},
        {iso1: 'ki', iso2: 'kik', iso: "Kikyuyu",                   local: "Gĩkũyũ"},
        {iso1: 'rw', iso2: 'kin', iso: "Kinyarwanda",               local: "Ikinyarwanda"},
        {iso1: 'ky', iso2: 'kir', iso: "Kirghiz",                   local: "Кыргызча, Кыргыз тили"},
        {iso1: '',   iso2: 'kmb', iso: "Kimbundu",                  local: ""},
        {iso1: '',   iso2: 'kok', iso: "Konkoni",                   local: ""},
        {iso1: 'kv', iso2: 'kom', iso: "Komi",                      local: "коми кыв"},
        {iso1: 'kg', iso2: 'kon', iso: "Kongo",                     local: "Kikongo"},
        {iso1: 'ko', iso2: 'kor', iso: "Korean",                    local: "한국어"},
        {iso1: '',   iso2: 'kos', iso: "Kosreaean",                 local: ""},
        {iso1: '',   iso2: 'kpe', iso: "Kpelle",                    local: ""},
        {iso1: '',   iso2: 'krc', iso: "Karacha-Balkar",            local: ""},
        {iso1: '',   iso2: 'kri', iso: "Karnelian",                 local: ""},
        {iso1: '',   iso2: 'kro', iso: "Kru Languages",             local: ""},
        {iso1: '',   iso2: 'kru', iso: "Kurukh",                    local: ""},
        {iso1: 'kj', iso2: 'kua', iso: "Kuanyama",                  local: "Kuanyama"},
        {iso1: '',   iso2: 'kum', iso: "kumyk",                     local: ""},
        {iso1: 'ku', iso2: 'kur', iso: "Kurdish",                   local: "Kurdî, كوردی‎"},
        {iso1: '',   iso2: 'kut', iso: "Kutenai",                   local: ""},
        {iso1: '',   iso2: 'lad', iso: "Ladino",                    local: ""},
        {iso1: '',   iso2: 'lah', iso: "Lahnda",                    local: ""},
        {iso1: '',   iso2: 'lam', iso: "Lamba",                     local: ""},
        {iso1: 'lo', iso2: 'lao', iso: "Lao",                       local: "ພາສາລາວ"},
        {iso1: 'la', iso2: 'lat', iso: "Latin",                     local: "Latin"},
        {iso1: 'lv', iso2: 'lav', iso: "Latvian",                   local: "Latviešu Valoda"},
        {iso1: '',   iso2: 'lez', iso: "Lezghian",                  local: ""},
        {iso1: 'li', iso2: 'lim', iso: "Limburgan",                 local: "Limburgs"},
        {iso1: 'ln', iso2: 'lin', iso: "Lingala",                   local: "Lingála"},
        {iso1: 'lt', iso2: 'lit', iso: "Lithuanian",                local: "lietuvių kalba"},
        {iso1: '',   iso2: 'lol', iso: "Mongo",                     local: ""},
        {iso1: '',   iso2: 'loz', iso: "Lozi",                      local: ""},
        {iso1: 'lb', iso2: 'itz', iso: "Luxembourgish",             local: "Lëtzebuergesch"},
        {iso1: '',   iso2: 'lua', iso: "Luba-Lulua",                local: ""},
        {iso1: 'lu', iso2: 'lub', iso: "Luba-Katanga",              local: "Kiluba"},
        {iso1: 'lg', iso2: 'lug', iso: "Ganda",                     local: "Luganda"},
        {iso1: '',   iso2: 'lui', iso: "Luiseno",                   local: ""},
        {iso1: '',   iso2: 'lun', iso: "Lunda",                     local: ""},
        {iso1: '',   iso2: 'luo', iso: "Luo",                       local: ""},
        {iso1: '',   iso2: 'lus', iso: "Lushai",                    local: ""},
        {iso1: 'mk', iso2: 'mkd', iso: "Macedonian",                local: "македонски јазик"},
        {iso1: 'mk', iso2: 'mac', iso: "Macedonian",                local: "македонски јазик"},
        {iso1: '',   iso2: 'mad', iso: "Madurese",                  local: ""},
        {iso1: '',   iso2: 'mag', iso: "Magahi",                    local: ""},
        {iso1: 'mh', iso2: 'mah', iso: "Marshallese",               local: "Kajin M̧ajeļ"},
        {iso1: '',   iso2: 'mai', iso: "Maithilli",                 local: ""},
        {iso1: '',   iso2: 'mak', iso: "Makasar",                   local: ""},
        {iso1: 'ml', iso2: 'mal', iso: "Malayalam",                 local: "മലയാളം"},
        {iso1: '',   iso2: 'man', iso: "Mandingo",                  local: ""},
        {iso1: 'mi', iso2: 'mri', iso: "Maori",                     local: "te reo Māori"},
        {iso1: '',   iso2: 'map', iso: "Austronesian Languages",    local: ""},
        {iso1: 'mr', iso2: 'mar', iso: "Marathi",                   local: "मराठी"},
        {iso1: '',   iso2: 'mas', iso: "Masai",                     local: ""},
        {iso1: 'ms', iso2: 'may', iso: "Malay",                     local: "بهاس ملايو"},
        {iso1: 'ms', iso2: 'msa', iso: "Malay",                     local: "بهاس ملايو"},
        {iso1: '',   iso2: 'mdf', iso: "Moksah",                    local: ""},
        {iso1: '',   iso2: 'mdr', iso: "Mandar",                    local: ""},
        {iso1: '',   iso2: 'men', iso: "Mende",                     local: ""},
        {iso1: '',   iso2: 'mga', iso: "Middle Irish",              local: ""},
        {iso1: '',   iso2: 'mic', iso: "Mi'kmaq; Micmac",           local: ""},
        {iso1: '',   iso2: 'min', iso: "Minangkabau",               local: ""},
        {iso1: '',   iso2: 'mis', iso: "Uncoded Languages",         local: ""},
        {iso1: '',   iso2: 'mkh', iso: "Mon-Khmer Languages",       local: ""},
        {iso1: 'mg', iso2: 'mlg', iso: "Malagasy",                  local: "fiteny malagasy"},
        {iso1: 'mt', iso2: 'mlt', iso: "Maltese",                   local: "Malti"},
        {iso1: '',   iso2: 'mnc', iso: "Manchu",                    local: ""},
        {iso1: '',   iso2: 'mni', iso: "Manipuri",                  local: ""},
        {iso1: '',   iso2: 'mno', iso: "Manobo Languages",          local: ""},
        {iso1: '',   iso2: 'moh', iso: "Mohawk",                    local: ""},
        {iso1: 'mn', iso2: 'mon', iso: "Mongolian",                 local: "Монгол хэл"},
        {iso1: '',   iso2: 'mos', iso: "Mossi",                     local: ""},
        {iso1: '',   iso2: 'mul', iso: "Multiple Languages",        local: ""},
        {iso1: '',   iso2: 'mun', iso: "Munda Languages",           local: ""},
        {iso1: '',   iso2: 'mus', iso: "Creek",                     local: ""},
        {iso1: '',   iso2: 'mwi', iso: "Mirandese",                 local: ""},
        {iso1: '',   iso2: 'mwr', iso: "Marwari",                   local: ""},
        {iso1: '',   iso2: 'myn', iso: "Mayan Languages",           local: ""},
        {iso1: '',   iso2: 'myv', iso: "Erzya",                     local: ""},
        {iso1: '',   iso2: 'nah', iso: "Nahuati Languages",         local: ""},
        {iso1: '',   iso2: 'nai', iso: "American Indian Languages", local: ""},
        {iso1: '',   iso2: 'nap', iso: "Neopolitan",                local: ""},
        {iso1: 'na', iso2: 'nau', iso: "Nauru",                     local: "Dorerin Naoero"},
        {iso1: 'nv', iso2: 'nav', iso: "Navajo",                    local: "Diné bizaad"},
        {iso1: 'nr', iso2: 'ndl', iso: "South Ndebele",             local: "isiNdebele"},
        {iso1: 'nd', iso2: 'nde', iso: "North Ndebele",             local: "isiNdebele"},
        {iso1: 'ng', iso2: 'ndo', iso: "Ndonga",                    local: "Owambo"},
        {iso1: '',   iso2: 'nds', iso: "Lower German",              local: ""},
        {iso1: 'ne', iso2: 'nep', iso: "Nepali",                    local: "नेपाली"},
        {iso1: '',   iso2: 'new', iso: "Nepal Bhasa",               local: ""},
        {iso1: '',   iso2: 'nia', iso: "Nias",                      local: ""},
        {iso1: '',   iso2: 'nic', iso: "Niger-Kordofanian Langs",   local: ""},
        {iso1: '',   iso2: 'niu', iso: "Niuean",                    local: ""},
        {iso1: 'nn', iso2: 'nno', iso: "Norwegian Nynorsk",         local: ""},
        {iso1: 'nb', iso2: 'nob', iso: "Norwegian Bokmål",          local: ""},
        {iso1: '',   iso2: 'nog', iso: "Nogai",                     local: ""},
        {iso1: '',   iso2: 'non', iso: "Old Norsk",                 local: ""},
        {iso1: 'no', iso2: 'nor', iso: "Norwegian",                 local: "Norsk"},
        {iso1: '',   iso2: 'nqo', iso: "N'Ko",                      local: ""},
        {iso1: '',   iso2: 'nso', iso: "Pedi",                      local: ""},
        {iso1: '',   iso2: 'nub', iso: "Nubian Languages",          local: ""},
        {iso1: '',   iso2: 'nwc', iso: "Old Newari",                local: ""},
        {iso1: 'ny', iso2: 'nya', iso: "Chichewa",                  local: "chiCheŵa, chinyanja"},
        {iso1: '',   iso2: 'nym', iso: "Nyamwezi",                  local: ""},
        {iso1: '',   iso2: 'nyn', iso: "Nyankole",                  local: ""},
        {iso1: '',   iso2: 'nyo', iso: "Nyoro",                     local: ""},
        {iso1: '',   iso2: 'nzi', iso: "Nzima",                     local: ""},
        {iso1: 'oc', iso2: 'oci', iso: "Occitan",                   local: "occitan, lenga d'òc"},
        {iso1: 'oj', iso2: 'oji', iso: "Ojobwa",                    local: ""},
        {iso1: 'or', iso2: 'ori', iso: "Oriya",                     local: "ଓଡ଼ିଆ"},
        {iso1: 'om', iso2: 'orm', iso: "Oromo",                     local: "Afaan Oromoo"},
        {iso1: '',   iso2: 'osa', iso: "Osage",                     local: ""},
        {iso1: 'os', iso2: 'oss', iso: "Ossetian",                  local: "ирон æвзаг"},
        {iso1: '',   iso2: 'ota', iso: "Ottoman Turkish",           local: ""},
        {iso1: '',   iso2: 'oto', iso: "Otomian Languages",         local: ""},
        {iso1: '',   iso2: 'paa', iso: "Papuan Languages",          local: ""},
        {iso1: '',   iso2: 'pag', iso: "Pangasinan",                local: ""},
        {iso1: '',   iso2: 'pal', iso: "Pahlavi",                   local: ""},
        {iso1: '',   iso2: 'pam', iso: "Pampanga",                  local: ""},
        {iso1: 'pa', iso2: 'pan', iso: "Panjabi",                   local: "ਪੰਜਾਬੀ"},
        {iso1: '',   iso2: 'pap', iso: "Papiamento",                local: ""},
        {iso1: '',   iso2: 'pau', iso: "Palauan",                   local: ""},
        {iso1: '',   iso2: 'peo', iso: "Old Persian",               local: ""},
        {iso1: '',   iso2: 'phi', iso: "Philippines Languages",     local: ""},
        {iso1: '',   iso2: 'phn', iso: "Phoenician",                local: ""},
        {iso1: 'pi', iso2: 'pli', iso: "Pali",                      local: "पाऴि"},
        {iso1: 'pl', iso2: 'pol', iso: "Polish",                    local: "Polszczyzna"},
        {iso1: '',   iso2: 'pon', iso: "Pohnpeian",                 local: ""},
        {iso1: 'pt', iso2: 'por', iso: "Portuguese",                local: "Português"},
        {iso1: '',   iso2: 'pra', iso: "Prakrit Languages",         local: ""},
        {iso1: '',   iso2: 'pro', iso: "Provençal",                 local: ""},
        {iso1: 'ps', iso2: 'pus', iso: "Pashto",                    local: "پښتو"},
        {iso1: 'qu', iso2: 'que', iso: "Quechua",                   local: "Runa Simi, Kichwa"},
        {iso1: '',   iso2: 'raj', iso: "Rajasthani",                local: ""},
        {iso1: '',   iso2: 'rap', iso: "Rapanui",                   local: ""},
        {iso1: '',   iso2: 'rar', iso: "Rarotongan",                local: ""},
        {iso1: '',   iso2: 'roa', iso: "Romance Languages",         local: ""},
        {iso1: 'rm', iso2: 'roh', iso: "Romansh",                   local: "Rumantsch Grischun"},
        {iso1: '',   iso2: 'rom', iso: "Romany",                    local: ""},
        {iso1: 'ro', iso2: 'rum', iso: "Romanian; Moldovan",        local: "Română"},
        {iso1: 'ro', iso2: 'ron', iso: "Romanian; Moldovan",        local: "Română"},
        {iso1: 'rn', iso2: 'run', iso: "Rundi",                     local: "Ikirundi"},
        {iso1: '',   iso2: 'rup', iso: "Aromanian",                 local: ""},
        {iso1: 'ru', iso2: 'rus', iso: "Russian",                   local: "Русский"},
        {iso1: '',   iso2: 'sad', iso: "Sandawe",                   local: ""},
        {iso1: 'sg', iso2: 'sag', iso: "Sango",                     local: "yângâ tî sängö"},
        {iso1: '',   iso2: 'sah', iso: "Yakut",                     local: ""},
        {iso1: '',   iso2: 'sai', iso: "South American Indian Lngs",local: ""},
        {iso1: '',   iso2: 'sal', iso: "Salishan Languages Langs",  local: ""},
        {iso1: '',   iso2: 'sam', iso: "Samaritan Aramaic",         local: ""},
        {iso1: 'sa', iso2: 'san', iso: "Sanskrit",                  local: "संस्कृतम्"},
        {iso1: '',   iso2: 'sas', iso: "Sasak",                     local: ""},
        {iso1: '',   iso2: 'sat', iso: "Santali",                   local: ""},
        {iso1: '',   iso2: 'scn', iso: "Sicilian",                  local: ""},
        {iso1: '',   iso2: 'sco', iso: "Scots",                     local: ""},
        {iso1: '',   iso2: 'sel', iso: "Selcup",                    local: ""},
        {iso1: '',   iso2: 'sem', iso: "Semetic Languages",         local: ""},
        {iso1: '',   iso2: 'sga', iso: "Old Irish",                 local: ""},
        {iso1: '',   iso2: 'sgn', iso: "Sign Languages",            local: ""},
        {iso1: '',   iso2: 'shn', iso: "Shan",                      local: ""},
        {iso1: '',   iso2: 'sid', iso: "Sidamo",                    local: ""},
        {iso1: 'si', iso2: 'sin', iso: "Sinhala",                   local: "සිංහල"},
        {iso1: '',   iso2: 'sio', iso: "Siouan Languages",          local: ""},
        {iso1: '',   iso2: 'sit', iso: "Sino-Tibetan Languages",    local: ""},
        {iso1: '',   iso2: 'sla', iso: "Slavic Languages",          local: ""},
        {iso1: 'sk', iso2: 'slo', iso: "Slovak",                    local: "Slovenčina"},
        {iso1: 'sk', iso2: 'slk', iso: "Slovak",                    local: "Slovenčina"},
        {iso1: 'sl', iso2: 'slv', iso: "Slovenian",                 local: "Slovenski Jezik"},
        {iso1: '',   iso2: 'sma', iso: "Southern Sami",             local: ""},
        {iso1: 'se', iso2: 'sme', iso: "Northern Sami",             local: "Davvisámegiella"},
        {iso1: '',   iso2: 'smi', iso: "Sami Languages",            local: ""},
        {iso1: '',   iso2: 'smj', iso: "Luli Sami",                 local: ""},
        {iso1: '',   iso2: 'smn', iso: "Inari Sami",                local: ""},
        {iso1: 'sm', iso2: 'smo', iso: "Samoan",                    local: "gagana fa'a Samoa"},
        {iso1: '',   iso2: 'sms', iso: "Skolt Sami",                local: ""},
        {iso1: 'sn', iso2: 'sna', iso: "Shona",                     local: "chiShona"},
        {iso1: 'sd', iso2: 'snd', iso: "Sindhi",                    local: "सिन्धी, سنڌي، سندھی‎"},
        {iso1: '',   iso2: 'snk', iso: "Sonike",                    local: ""},
        {iso1: '',   iso2: 'sog', iso: "Sogdian",                   local: ""},
        {iso1: 'so', iso2: 'som', iso: "Somali",                    local: "Soomaaliga, af Soomaali"},
        {iso1: '',   iso2: 'son', iso: "Songhai Languages",         local: ""},
        {iso1: 'st', iso2: 'sot', iso: "Southern Sotho",            local: "Sesotho"},
        {iso1: 'es', iso2: 'spa', iso: "Spanish",                   local: "Español"},
        {iso1: 'sc', iso2: 'srd', iso: "Sardinian",                 local: "sardu"},
        {iso1: '',   iso2: 'srn', iso: "Sranan Tongo",              local: ""},
        {iso1: 'sr', iso2: 'srp', iso: "Serbian",                   local: "српски језик"},
        {iso1: '',   iso2: 'srr', iso: "Serer",                     local: ""},
        {iso1: '',   iso2: 'ssa', iso: "Nilo-Saharan Languages",    local: ""},
        {iso1: 'ss', iso2: 'ssw', iso: "Swati",                     local: "SiSwati"},
        {iso1: '',   iso2: 'suk', iso: "Sukuma",                    local: ""},
        {iso1: 'su', iso2: 'sun', iso: "Sudanese",                  local: "Basa Sunda"},
        {iso1: '',   iso2: 'sus', iso: "Susu",                      local: ""},
        {iso1: '',   iso2: 'sux', iso: "Sumerian",                  local: ""},
        {iso1: 'sw', iso2: 'swa', iso: "Swahili",                   local: "Kiswahili"},
        {iso1: 'sv', iso2: 'swe', iso: "Swedish",                   local: "Svenska"},
        {iso1: '',   iso2: 'syc', iso: "Classical Syriac",          local: ""},
        {iso1: '',   iso2: 'syr', iso: "Syriac",                    local: ""},
        {iso1: 'ty', iso2: 'tah', iso: "Tahitian",                  local: "Reo Tahiti"},
        {iso1: '',   iso2: 'tai', iso: "Tai Languages",             local: ""},
        {iso1: 'ta', iso2: 'tam', iso: "Tamil",                     local: "தமிழ்"},
        {iso1: 'tt', iso2: 'tat', iso: "Tartar",                    local: "татар теле, tatar tele"},
        {iso1: 'te', iso2: 'tel', iso: "Telugu",                    local: "తెలుగు"},
        {iso1: '',   iso2: 'tem', iso: "Timne",                     local: ""},
        {iso1: '',   iso2: 'ter', iso: "Tereno",                    local: ""},
        {iso1: '',   iso2: 'tet', iso: "Tetum",                     local: ""},
        {iso1: 'tg', iso2: 'tgk', iso: "Tajik",                     local: "тоҷикӣ, toçikī, تاجیکی‎"},
        {iso1: 'tl', iso2: 'tgl', iso: "Tagalog",                   local: "Wikang Tagalog"},
        {iso1: 'th', iso2: 'tha', iso: "Thai",                      local: "ไทย"},
        {iso1: '',   iso2: 'tig', iso: "Tigre",                     local: ""},
        {iso1: 'ti', iso2: 'tir', iso: "Tigrinya",                  local: "ትግርኛ"},
        {iso1: '',   iso2: 'tiv', iso: "Tiv",                       local: ""},
        {iso1: '',   iso2: 'tkl', iso: "Tokelau",                   local: ""},
        {iso1: '',   iso2: 'tih', iso: "Klingon",                   local: ""},
        {iso1: '',   iso2: 'tli', iso: "Tlingit",                   local: ""},
        {iso1: '',   iso2: 'tmh', iso: "Tamashek",                  local: ""},
        {iso1: '',   iso2: 'tog', iso: "Tonga (Nyasa)",             local: ""},
        {iso1: 'to', iso2: 'ton', iso: "Tonga",                     local: "Faka Tonga"},
        {iso1: '',   iso2: 'tpi', iso: "Tok Pisin",                 local: ""},
        {iso1: '',   iso2: 'tsi', iso: "Tsimshian",                 local: ""},
        {iso1: 'tn', iso2: 'tsn', iso: "Tswana",                    local: "Setswana"},
        {iso1: 'ts', iso2: 'tso', iso: "Tsonga",                    local: "Xitsonga"},
        {iso1: 'tk', iso2: 'tuk', iso: "Turkmen",                   local: "Türkmen, Түркмен"},
        {iso1: '',   iso2: 'tum', iso: "Tumbuka",                   local: ""},
        {iso1: '',   iso2: 'tup', iso: "Tupi Languages",            local: ""},
        {iso1: 'tr', iso2: 'tur', iso: "Turkish",                   local: "Türkçe"},
        {iso1: '',   iso2: 'tut', iso: "Asiatic Languages",         local: ""},
        {iso1: '',   iso2: 'tvi', iso: "Tuvala",                    local: ""},
        {iso1: 'tw', iso2: 'twi', iso: "Twi",                       local: "Twi"},
        {iso1: '',   iso2: 'tyv', iso: "Tuvinian",                  local: ""},
        {iso1: '',   iso2: 'udm', iso: "Udmurt",                    local: ""},
        {iso1: '',   iso2: 'uga', iso: "Ugaritic",                  local: ""},
        {iso1: 'ug', iso2: 'uig', iso: "Uighur",                    local: "ئۇيغۇرچە‎, Uyghurche"},
        {iso1: 'uk', iso2: 'ukr', iso: "Ukrainian",                 local: "Українська"},
        {iso1: '',   iso2: 'umb', iso: "Umbundu",                   local: ""},
        {iso1: '',   iso2: 'und', iso: "Undetermined",              local: ""},
        {iso1: 'ur', iso2: 'urd', iso: "Urdu",                      local: "اردو"},
        {iso1: 'uz', iso2: 'uzb', iso: "Uzbek",                     local: "Oʻzbek, Ўзбек, أۇزبېك‎"},
        {iso1: '',   iso2: 'vai', iso: "Vai",                       local: ""},
        {iso1: 've', iso2: 'ven', iso: "Venda",                     local: "Tshivenḓa"},
        {iso1: 'vi', iso2: 'vie', iso: "Vietnamese",                local: "Tiếng Việt"},
        {iso1: 'vo', iso2: 'vol', iso: "Volapük",                   local: ""},
        {iso1: '',   iso2: 'vot', iso: "Votic",                     local: ""},
        {iso1: '',   iso2: 'wak', iso: "Wakashan Languages",        local: ""},
        {iso1: '',   iso2: 'wal', iso: "Wolaitta",                  local: ""},
        {iso1: '',   iso2: 'war', iso: "Waray",                     local: ""},
        {iso1: '',   iso2: 'was', iso: "Washo",                     local: ""},
        {iso1: '',   iso2: 'wen', iso: "Sorbian Languages",         local: ""},
        {iso1: 'wa', iso2: 'wln', iso: "Waloon",                    local: "Walon"},
        {iso1: 'wo', iso2: 'wol', iso: "Wolof",                     local: "Wollof"},
        {iso1: '',   iso2: 'xal', iso: "Kalmyk; Oirat",             local: ""},
        {iso1: 'xh', iso2: 'xho', iso: "Xhosa",                     local: "isiXhosa"},
        {iso1: '',   iso2: 'yao', iso: "Yao",                       local: ""},
        {iso1: '',   iso2: 'yap', iso: "Yapese",                    local: ""},
        {iso1: 'yi', iso2: 'yid', iso: "Yiddish",                   local: "ייִדיש"},
        {iso1: 'yo', iso2: 'yor', iso: "Yoruba",                    local: "Yorùbá"},
        {iso1: '',   iso2: 'ypk', iso: "Yupik Languages",           local: ""},
        {iso1: '',   iso2: 'zap', iso: "Zaptec",                    local: ""},
        {iso1: '',   iso2: 'zbl', iso: "Blissymbols",               local: ""},
        {iso1: '',   iso2: 'zen', iso: "Zenaga",                    local: ""},
        {iso1: '',   iso2: 'zgh', iso: "Moroccan Tamazight",        local: ""},
        {iso1: 'za', iso2: 'zha', iso: "Zhuang",                    local: "Saɯ cueŋƅ, Saw cuengh"},
        {iso1: '',   iso2: 'znd', iso: "Zande Languages",           local: ""},
        {iso1: 'zu', iso2: 'zul', iso: "Zulu",                      local: "isiZulu"},
        {iso1: '',   iso2: 'znn', iso: "Zuni",                      local: ""},
        {iso1: '',   iso2: 'zxx', iso: "No Content",                local: ""},
        {iso1: '',   iso2: 'zza', iso: "Zaza; Dimilli",             local: ""},
    ];


    /*****
     * The master database of all ISO categorized languages.  Although it's NOT a
     * relational DBMS, it has been configurated to provide data on those languages
     * that have been registered.  Note that modern languages, past and ancient
     * languages, as well as language groups have been entered.
    *****/
    singleton(class Languages {
        constructor() {
            this.all = {};
            this.iso1 = {};
            this.iso2 = {};

            for (let language of languages) {
                if (language.iso1) {
                    this.iso1[language.iso1] = language;
                }

                this.iso2[language.iso2] = language;

                if (language.iso1 && !(language.iso1 in this.all)) {
                    this.all[language.iso1] = language;
                }

                if (!(language.iso2 in this.all)) {
                    this.all[language.iso2] = language;
                }
            }
        }

        get(code) {
            let lang = this.all[code.toLowerCase()];
            return lang ? clone(lang) : null;
        }

        get639_1(code) {
            let lang = this.iso1[code.toLowerCase()];
            return lang ? clone(lang) : null;
        }

        get639_2(code) {
            let lang = this.iso2[code.toLowerCase()];
            return lang ? clone(lang) : null;
        }

        getChoices() {
            return languages
            .filter(lang => lang .iso1 != '')
            .map(lang => ({ value: lang.iso1, text: lang.iso }));
        }

        listIso1() {
            return clone(this.iso1);
        }

        listAll() {
            return clone(this.all);
        }

        selectIso1(stringSet) {
            let languages = {};

            for (let iso1 of stringSet) {
                if (iso1 in this.iso1) {
                    languages[iso1] = clone(this.iso1[iso1]);
                }
            }

            return languages;
        }
    });
})();
